// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhK_RQHJkR8NC5FzJ2L38NCvl1pf1VKk',
    appId: '1:410302709481:web:bfbbb96e54c434f83cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    authDomain: 'fire-base-autentifikasi.firebaseapp.com',
    databaseURL: 'https://product-db-fa6c8-default-rtdb.firebaseio.com/',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    measurementId: 'G-VPY30XBZQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLgdlViJMAuq-32pnIsswTNB1AeaYZ_Y',
    appId: '1:410302709481:android:9cd7dc448a6e48033cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqmDmgitL8YxhOvjNfidY5HuigBmiMDs',
    appId: '1:410302709481:ios:26d8c91a997c8f573cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    iosClientId:
        '410302709481-afod45k3rlaimo5prfksi0jqmluo04pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.product1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCqmDmgitL8YxhOvjNfidY5HuigBmiMDs',
    appId: '1:410302709481:ios:26d8c91a997c8f573cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    iosClientId:
        '410302709481-afod45k3rlaimo5prfksi0jqmluo04pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.product1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyhK_RQHJkR8NC5FzJ2L38NCvl1pf1VKk',
    appId: '1:410302709481:web:ccfa51d2e8f883e53cba78',
    messagingSenderId: '410302709481',
    projectId: 'fire-base-autentifikasi',
    authDomain: 'fire-base-autentifikasi.firebaseapp.com',
    databaseURL: 'https://fire-base-autentifikasi-default-rtdb.firebaseio.com',
    storageBucket: 'fire-base-autentifikasi.appspot.com',
    measurementId: 'G-7B9T2NFTYM',
  );
}
